### ISSUE TITLE
Sorry to Hear he did it to you also.

### ISSUE THREAD

**Issue by Psycholiquid71** [Alzar/bluesky#1]
Now I think you guys understand why I did what I did. He is a scammer and needs to be pushed out of fivem all together, He will be doing the same thing to Definition RP next just give him a little time to start his "I'm broke and need money" crap he always pulls.

**Comment by Alzar** [comment]
I mean I understand, but still don't agree fully with what you did.

Difference between what we did was this code was, and is, Mine & Discworld's. Disc originally agreed to let me use it with PW/React as the original project it was used for what dead. Chris then stole it and ran of with it without asking either of us if he could use it. I also didn't release anything that wasn't part of my codebase such as maps or vehicles. As well as spoke with Disc & Creaktive about releasing it and asking if there was anything they'd like removed before doing so.

Though that being said nothing you did warrants doxing you on stream, which he did several times just as an FYI. Sadly he deleted the VODs. But yeah, seems he found a home that will accept him for the worthless shitstain he is. Which is all the more funnier considering that servers history & the fact they have a FiveM mod on their team. Guess breaking TOS is fine as long as you have a FiveM mod on staff 😂. Guess that speaks volumes at how worthless that entire FiveM "community" is
