### ISSUE TITLE
base convar

### ISSUE THREAD

**Issue by yagizher** [Alzar/bluesky#2]
![image](https://user-images.githubusercontent.com/52376710/89463576-d0a86b80-d777-11ea-9acd-d370a2fe2597.png)

this issue pops up when server starts.

And when i try  to connect, i got the warning:
"The Blue Sky Server has not yet finished loading, please try again in a few minutes."

**Comment by Alzar** [comment]
`This code is being released as-is with no guarantee of working out of the box. In fact it will not work without extensive decoupling from a custom Invision Power Board application that was written for Blue Sky.`

If you can't read that code and determine the issue, I'd suggest against trying to use this ;)
